### ISSUE TITLE
Greek ligatures

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [dbenjaminmiller/garamond-libre#11]
It would be awesome if you implemented Greek ligatures in this font. On Wikimedia Commons I discovered some good examples to show how does these ligatures looks like. Click _Original File_ to see them clearly when you access the file description page.

Books made with _Grecs du roi_, a Greek typeface by Claude Garamond
https://commons.wikimedia.org/wiki/Category:Grecs_du_Roi
A book _Illustrirte Geschichte der Buchdruckerkunst_ has a section "Griechisch" (page 570-573) including Greek sample texts with such typeface.
https://commons.wikimedia.org/w/index.php?title=Category:Illustrirte_Geschichte_der_Buchdruckerkunst_(Faulmann)&filefrom=Illustrirte+Geschichte+der+Buchdruckerkunst+%28Faulmann%29+401.jpg#mw-category-media

**Comment by dbenjaminmiller** [comment]
The upright is a Didot. So it would make no sense having these ligatures in that style. In the italic, there are already some ligatures and I don't have a strong interest in adding more.
