### ISSUE TITLE
could not implement font in LaTeX (lyx), because tds is no longer available

### ISSUE THREAD

**Issue by SusaKlim** [dbenjaminmiller/garamond-libre#13]
Hello Benjamin,
I would like to use your font for my thesis but was not able to implement it, mainly because I could not find a tds ressource. Is there a way to install the font and/or request a tds folder from you?

Thank you very much in advance, kind regards,
Susanne

**Comment by dbenjaminmiller** [comment]
Hi Susanne,
My apologies for the late response. The font has been available in TDS form from CTAN since its original release.
