### ISSUE TITLE
huge x-height value

### ISSUE THREAD

**Issue by ousia** [dbenjaminmiller/garamond-libre#2]
@dbenjaminmiller,

many thanks for your release of _Garamond Libre_, which I came to know an how ago.

My first test was with ConTeXt and I found an issue with the x-height value. The actual x-height value is 0.55ex (instead of 1ex).

The following image (linked to a PDF file) shows the issue:

[![glibre](https://user-images.githubusercontent.com/203767/79157961-ca137400-7dd5-11ea-9085-0f973eb283e5.png)](https://github.com/dbenjaminmiller/garamond-libre/files/4471697/glibre.pdf)

Would it be possible to fix this?

Many thanks for your excellent work and your help.

**Comment by dbenjaminmiller** [comment]
I can try to fix it, yes … alternatively if you download FontForge you can send a PR with the tweak since you have the ConTeXt setup to test it already.

**Comment by ousia** [comment]
Going to send a PR in the next minutes (too late here).
