### ISSUE TITLE
Comparison with EB Garamond

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [dbenjaminmiller/garamond-libre#6]
Hi! As a fan of [EB Garamond](https://github.com/georgd/EB-Garamond) I would like to know the main differences between both fonts. I'm also using [Garamond-Math](https://github.com/YuanshengZhao/Garamond-Math) for typesetting math matching the same font as the body of the text.

I'm always curious about all the possible ways to typeset my documents (including math) in beautiful Garamond.

EB Garamond is also available [in Google Fonts](https://fonts.google.com/specimen/EB+Garamond) so that may be an advantage for web usage.

Thanks in advance,
Rodrigo

**Comment by dbenjaminmiller** [comment]
![image](https://user-images.githubusercontent.com/43855846/80541817-d7a22f80-8979-11ea-8218-63f0192a8399.png)
Not an issue.
